### ISSUE TITLE
Arduino compile error 

### ISSUE THREAD

**Issue by audiobugz** [gillham/logic_analyzer#15]
Hi, there thanks for this valuable tool. I have downloaded the files from this page and OLS logic sniffer from the link version 0.9.17 and have tried to add the 2 files to the plugin folder but theirs new versions so i have left them alone. The problem I'm having is

Arduino: 1.5.8 (Mac OS X), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

logic_analyzer.ino: In function 'void loop()':
logic_analyzer.ino:298:27: error: 'captureInline4mhz' was not declared in this scope
Error compiling.

and many more errors for the 4MHZ file is this some thing you could please help me with. 

Thank you for taking your time to make this!! :)

**Comment by gillham** [comment]
Any feedback on whether it is working or not?  Let me know.
