### ISSUE TITLE
Support for ATmega32u4 (Leonardo boards)

### ISSUE THREAD

**Issue by rmetrich** [gillham/logic_analyzer#23]
Hi,
do you plan to add the necessary code to have this work with Leonardo boards?
I found some (old) code on the Arduino forum but it doesn't seem to work (http://forum.arduino.cc/index.php?topic=52881.msg1128160#msg1128160).
Thanks

**Comment by gillham** [comment]
Have you tried the agla_leonardo branch of the logic_analyzer code?

**Comment by rmetrich** [comment]
Oups, missed that branch!
Sorry for the noise.

**Comment by gillham** [comment]
Let me know if it works for you, I haven't tested that code all that much and there could be some issues with interrupts shut off for so long with the USB etc.
