### ISSUE TITLE
less channels, more samples ?

### ISSUE THREAD

**Issue by d-a-v** [gillham/logic_analyzer#24]
Would it be possible to analyse only 4 channels and put two of them in each memory byte in order to increase the time range by two ?

**Comment by gillham** [comment]
It is possible, but takes additional cycles to read the upper & lower 4 bits, shifting etc.  So sample rates would be lower, though the unrolled method might help there.
I think it would be too much complexity for the value at the moment, but at some point it might be worth investigating.
