### ISSUE TITLE
Detection failed! null on LogicSniffer v0.9.7.2

### ISSUE THREAD

**Issue by Sekhmet** [gillham/logic_analyzer#34]
Hi,
I just love this project and wanted to try this, but sadly it doesn't work for me. I think I'm doing something wrong. I've compiled logic_analyzer (loaded all 3 files, compiled them succesfuly and loaded on my board), then I installed LogicSniffer v0.9.7.2, and wanted to start capture - Connection type serial port, port selected, speed 115200bps and device type Arduino Generic Logic Analyzer, but it doesn't capture anything. When I click on "Show device metadata" it prints "Detection failed! null"
When I click on this test button both TX/RX LEDs blink on my board.

I'm using RobotDyn NANO Arduino with ATmega328, LogicSniffer v0.9.7.2 and Windows 10.

Any ideas what I'm doing wrong?

Thanks.

**Comment by dhiltonp** [comment]
It sounds like you're pointing using the wrong port.

**Comment by Sekhmet** [comment]
Thanks,

I recompiled it few times and suddently capturing works, but detection has
same problem (it doesn't detect device in capture window)/

pon., 11 kwi 2016, 14:52 David Hilton użytkownik <notifications@github.com>
napisał:

> It sounds like you're pointing using the wrong port.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gillham/logic_analyzer/issues/34#issuecomment-208324689>
>
-- 
Wiktor Tkaczyński, Sekhmet

**Comment by gillham** [comment]
Please re-open if this is still a problem.
