### ISSUE TITLE
Support for Arduino Due

### ISSUE THREAD

**Issue by 12458** [gillham/logic_analyzer#35]
Hi,
Do you plan to add support for the Arduino due?

**Comment by karawin** [comment]
It's remind me an old release i made see https://github.com/karawin/logic_analyzer

**Comment by iddq** [comment]
Does it support due at the moment?

**Comment by gillham** [comment]
If you want to do a pull request against the current repository in a 'logic_analyzer_due' or similar directory, I can look at it.
I'm splitting it out so we can have:
logic_analyzer (original AVR ATMega pre-USB) 
logic_analyzer_leonardo (ATMega32U4
...future...
logic_analyzer_due (possible future ARM)
logic_analyzer_esp32
logic_analyzer_esp8266
logic_analyzer_esp32c3 (RISC-V)
etc...
