### ISSUE TITLE
It records for ~300 ms then stops. how can I make it go longer?

### ISSUE THREAD

**Issue by amrelk** [gillham/logic_analyzer#36]
Title is fairly self explanatory

**Comment by dhiltonp** [comment]
Increase buffer size (requires compatible hardware), or decrease sample rate. Alternatively, try to get triggering working so that it records exactly when you need it to.

**Comment by gillham** [comment]
Triggering and lower sample rates should help you out.  I’ve tested a few combinations of simple triggers. 
Let me know if you’re still having trouble.
