### ISSUE TITLE
how i can use arduino uno i cant build the project 

### ISSUE THREAD

**Issue by abdelrahma22** [gillham/logic_analyzer#42]

**Comment by gillham** [comment]
Make sure you have a directory called 'logic_analyzer' with these files:
logic_analyzer.ino
logic_analyzer_inline_2mhz.ino
logic_analyzer_inline_4mhz.ino

On Windows that should be C:\Users\<your userid>\Documents\Arduino\logic_analyzer\
On a Mac it would be ~/Documents/Arduino/logic_analyzer

If you can't get it to work, open a new issue with some details, screenshot, something.
