### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by abdelrahma22** [gillham/logic_analyzer#43]
Arduino: 1.6.13 (Windows 10), Board: "Arduino/Genuino Uno"

C:\Users\EssaM\AppData\Local\Temp\cclwLT9s.ltrans0.ltrans.o: In function `main':

cclwLT9s.ltrans0.o:(.text.startup+0x210): undefined reference to `captureInline4mhz()'

cclwLT9s.ltrans0.o:(.text.startup+0x21e): undefined reference to `captureInline2mhz()'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by stickbreaker** [comment]
@abdelrahma22 
copy all of the sketches into one directory.

**Comment by abdelrahma22** [comment]
i had but no good

**Comment by abdelrahma22** [comment]
can you give me binary file for ardyuno uno

**Comment by stickbreaker** [comment]
[Logic_Analyzer.ino.standard.zip](https://github.com/gillham/logic_analyzer/files/1823274/Logic_Analyzer.ino.standard.zip)

**Comment by abdelrahma22** [comment]
it compiled successfully but i cant run the analyzer please help me

**Comment by stickbreaker** [comment]
upload the sketch to the UNO

What Serial port is the UNO on?

have you downloaded the OLS client?

Download [ols client](https://www.lxtreme.nl/ols/ols-0.9.7.2-full.zip), extract the entire zip file

navigate to where you extracted the zip file

double click on run.bat

in OLS
  Capture>Device>OpenBench Logic Sniffer
  Capture>Begin Capture - Connection
    Connection Type > Serial Port
    Analyzer Port > UNO PORT from above
    PortSpeed> 115200
    DeviceType> Arduino Generic LogicAnalyzer
    Show Device MetaData>
      LEDs should blink on Uno,  
          My info: DeviceType: AGLAv0
          Firmware: 0.13
          Protocol 2
 Capture>Begin Capture - Triggers
   Uncheck trigger enabled:  until you need them
 Capture>Begin Capture - Acquisition
   sampling Rate: select one
   Record size: what ever, with a uno 1k is max

 Capture>Begin Capture 
   click "Capture"

**Comment by abdelrahma22** [comment]
i had 5 channel how i connect them in arduino to the project

**Comment by stickbreaker** [comment]
connect A0 .. A5

**Comment by stickbreaker** [comment]
This SUMP protocol compatible logic analyzer for the Arduino board supports
5 channels consisting of digital pins 8-12, which are the first 5 bits (0-4)
of PORTB. Arduino pin 13 / bit 5 is the Arduino LED, bits 6 & 7 are the
crystal oscillator pins.

D8.. D13

**Comment by abdelrahma22** [comment]
which the pin is analog input

**Comment by stickbreaker** [comment]
a logic analyzer is a digital representation of  the signal either on or off, this system cannot display an analog signal.

**Comment by abdelrahma22** [comment]
how can i use trigger to start capturing with start condition

**Comment by Escalion** [comment]
@abdelrahma22 - Read the README. You need to use a SUMP client and set the trigger there.

**Comment by gillham** [comment]
I'll add some verbiage to the README to make sure people are properly creating the 'logic_analyzer' directory in their sketchbook and putting the three files in there.  Apparently not everyone knows how to use 'git clone' to get things off github, so I need to improve the docs. :)
