### ISSUE TITLE
Please make this installable through arduino library manager

### ISSUE THREAD

**Issue by Harvie** [gillham/logic_analyzer#46]
If you add file `library.properties`, you can then request this for adition in arduino library manager here: https://github.com/arduino/arduino/issues
This will allow people to download and install this to their arduino using few simple clicks.

Here is example of such installable repository: https://github.com/Harvie/RotaryDial/

**Comment by gillham** [comment]
This isn't really meant to be a library, it is a standalone application.  Does that make sense?

**Comment by Harvie** [comment]
Yes it does. Some projects are distributed this way already. You install "library", then go to "examples" in arduino menu and install the application. It's bit more user friendly than having to download package and manualy copy it to arduino IDE. For example the GRBL is installed in similar manner.

**Comment by gillham** [comment]
Ok, I've rearranged the repository to support installing via the 'Add .ZIP Library' in the Arduino IDE.  Tested with Arduino IDE 2.2.1 on Linux.

Added to the repositories.txt via https://github.com/arduino/library-registry/pull/3432

**Comment by gillham** [comment]
This is now available in the Arduino IDE.  Search for 'LogicAnalyzer'
